name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' || github.event_name != 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test summary
        run: npx github-actions-ctrf@0.0.50-rc.5 summary ctrf-reports/ctrf-report.json
      - name: Test historical
        run: npx github-actions-ctrf@0.0.50-rc.5 historical ctrf-reports/ctrf-report.json --annotate false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test suite folded
        run: npx github-actions-ctrf@0.0.50-rc.5 suite-folded ctrf-reports/ctrf-report.json --annotate false
      - name: Test failed
        run: npx github-actions-ctrf@0.0.50-rc.5 failed ctrf-reports/ctrf-report.json --annotate false
      - name: Test failed rate
        run: npx github-actions-ctrf@0.0.50-rc.5 failed-rate ctrf-reports/ctrf-report.json --annotate false --title "Failed rate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test failed folded
        run: npx github-actions-ctrf@0.0.50-rc.5 failed-folded ctrf-reports/ctrf-report.json --annotate false
      - name: Test flaky
        run: npx github-actions-ctrf@0.0.50-rc.5 flaky ctrf-reports/ctrf-report.json --annotate false
      - name: Test flaky rate
        run: npx github-actions-ctrf@0.0.50-rc.5 flaky-rate ctrf-reports/ctrf-report.json --annotate false --title "Flaky rate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test ai
        run: npx github-actions-ctrf@0.0.50-rc.5 ai ctrf-reports/ctrf-report.json --annotate false
      - name: Test skipped
        run: npx github-actions-ctrf@0.0.50-rc.5 skipped ctrf-reports/ctrf-report.json --annotate false
      - name: Test custom summary
        run: npx github-actions-ctrf@0.0.50-rc.5 custom ctrf-reports/ctrf-report.json templates/custom-summary.hbs --annotate false
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
